/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#001f2a',
        'surface-bright': '#fbf9f0',
        'on-secondary': '#ffffff',
        'surface-dim': '#dcdad1',
        'surface-container': '#f0eee5',
        'on-primary': '#ffffff',
        'secondary-fixed': '#cee5ff',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#97ceea',
        'tertiary': '#27627b',
        'inverse-primary': '#93cdf8',
        'on-primary-container': '#fcfcff',
        'surface-container-low': '#f6f4eb',
        'secondary': '#3a6286',
        'primary-fixed-dim': '#93cdf8',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#41484e',
        'error': '#ba1a1a',
        'primary-fixed': '#c8e6ff',
        'inverse-on-surface': '#f3f1e8',
        'on-primary-fixed': '#001e2f',
        'on-secondary-fixed': '#001d33',
        'on-secondary-container': '#355d81',
        'outline-variant': '#c0c7cf',
        'surface-tint': '#226489',
        'secondary-fixed-dim': '#a3caf4',
        'primary': '#1f6187',
        'tertiary-fixed': '#bfe8ff',
        'background': '#fbf9f0',
        'surface-variant': '#e4e3da',
        'on-error': '#ffffff',
        'on-tertiary-container': '#fbfdff',
        'error-container': '#ffdad6',
        'on-surface': '#1b1c17',
        'surface-container-highest': '#e4e3da',
        'on-error-container': '#93000a',
        'surface-container-high': '#eae8df',
        'on-secondary-fixed-variant': '#1f4a6c',
        'tertiary-container': '#437b95',
        'primary-container': '#3e7aa1',
        'surface': '#fbf9f0',
        'inverse-surface': '#30312b',
        'on-primary-fixed-variant': '#004c6e',
        'on-tertiary-fixed-variant': '#054d65',
        'outline': '#71787f',
        'on-background': '#1b1c17',
        'secondary-container': '#aed5ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'margin-mobile': '20px',
        'margin-desktop': '48px',
        'gutter-mobile': '16px',
        'gutter-desktop': '24px',
        'container-max': '1440px',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      maxWidth: {
        container: '1440px',
      },
    },
  },
  plugins: [],
}
